name: 'Check comments using Comment Corrector'

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Analyse Commets Using Comment Corrector Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Comments
        uses: clodaghwalsh17/comment-corrector@v1.2
        with:
          custom-words-file: 'my_dictionary.txt'
          
