name: 'Check comments using Comment Corrector'

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Use Comment Corrector Action
    # continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cat file_a.py
        run: cat file_a.py
#       - name: Check Comments
#         uses: clodaghwalsh17/comment-corrector@betav9
