name: 'Check comments using Comment Corrector'

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Use Comment Corrector Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: clodaghwalsh17/comment-corrector
          ref: beta
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/comment-corrector
      
      - name: Check Comments
        uses: ./.github/actions/comment-corrector